/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class common_utils_radix_RadixTreeJNI */

#ifndef _Included_common_utils_radix_RadixTreeJNI
#define _Included_common_utils_radix_RadixTreeJNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     common_utils_radix_RadixTreeJNI
 * Method:    initialize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_common_utils_radix_RadixTreeJNI_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     common_utils_radix_RadixTreeJNI
 * Method:    findEntities
 * Signature: (JLjava/lang/String;)[Lcommon/utils/radix/EntityMatch;
 */
JNIEXPORT jobjectArray JNICALL Java_common_utils_radix_RadixTreeJNI_findEntities
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     common_utils_radix_RadixTreeJNI
 * Method:    addEntity
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_common_utils_radix_RadixTreeJNI_addEntity
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     common_utils_radix_RadixTreeJNI
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_common_utils_radix_RadixTreeJNI_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif